### ISSUE TITLE
Extension does not work with the new AWS UI

### ISSUE THREAD

**Issue by lpelleau** [jncharon/aws_console_extension#3]
Hello,

I have been using and enjoying this extension for a while now!

Unfortunately, AWS updated their UI, and the extension doesn't seem to be working anymore.

Best,
Loic

**Comment by jncharon** [comment]
Hi Loic,

Fixing won't be easy as AWS now uses random CSS class names like "Be8bmUkBQAdWUiekMBHKP". 
I'll see what I can do !

Best regards,
Jean-Noël

**Comment by jncharon** [comment]
I have a version which seems to run, would you like to test it ?

**Comment by lpelleau** [comment]
I'd love to :)

**Comment by jncharon** [comment]
You can download it here, unpack it and load the extension as an "unpacked extension" : http://www.charon.org/aws_console_extension.zip

**Comment by lpelleau** [comment]
it doesn't seem to work, but I see `Region : -Ireland-` in the console still

**Comment by lungdart** [comment]
Any update on this fix?

**Comment by mrMemfis** [comment]
Fix is ready https://github.com/jncharon/aws_console_extension/pull/5
